# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq
import seaborn as sns
import matplotlib as map
import matplotlib.pyplot as plt
import datetime as dt

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

import warnings
warnings.filterwarnings('ignore')

# Data Import

In [30]:
#Creating an empty dataframe.
df = pd.DataFrame()
#Printing shape of the dataframe
print(df.shape)

(0, 0)

We are creating a function to import the data and append all the data to the environment data frame.

In [31]:
def read_merge_data (file_path):
    global df
    var_tab = pq.read_table(file_path)
    temp_df = var_tab.to_pandas()
    df = df.append(temp_df, ignore_index = True)
    print(f"{df.shape} records hvae been appended")

In [32]:
#Creating a list of all the files that needs to be imported
file_name = [
     './work/green_tripdata_2022-01.parquet',
     './work/green_tripdata_2022-02.parquet',
     './work/green_tripdata_2022-03.parquet',
     './work/green_tripdata_2022-04.parquet',
     './work/green_tripdata_2022-05.parquet',
     './work/green_tripdata_2022-06.parquet',
     './work/green_tripdata_2022-07.parquet',
     './work/green_tripdata_2022-08.parquet',
     './work/green_tripdata_2022-09.parquet',
     './work/green_tripdata_2022-10.parquet',
     './work/green_tripdata_2022-11.parquet',
     './work/green_tripdata_2022-12.parquet',
     './work/green_tripdata_2023-01.parquet']

In [33]:
#Calling the defined function [read_merge(file_path)] to import data
for i in file_name:
    print(f"Loading {i} file.")
    read_merge_data(i)
    print(f"-----------------------------------File Loaded {i} ----------------------------------------")

Loading ./work/green_tripdata_2022-01.parquet file.
(62495, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-01.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-02.parquet file.
(131894, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-02.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-03.parquet file.
(210431, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-03.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-04.parquet file.
(286567, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-04.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-05.parquet file.
(363458, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-05.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-06.parquet file.
(437176, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-06.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-07.parquet file.
(501368, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-07.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-08.parquet file.
(567297, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-08.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-09.parquet file.
(636328, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-09.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-10.parquet file.
(705650, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-10.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-11.parquet file.
(767963, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-11.parquet ----------------------------------------
Loading ./work/green_tripdata_2022-12.parquet file.
(840402, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2022-12.parquet ----------------------------------------
Loading ./work/green_tripdata_2023-01.parquet file.
(908613, 20) records hvae been appended
-----------------------------------File Loaded ./work/green_tripdata_2023-01.parquet ----------------------------------------

In [34]:
taxizonefilepath = './work/taxi+_zone_lookup.csv'
taxizone_df = pd.read_csv(taxizonefilepath)
print(taxizone_df.shape)
print(taxizone_df.info())
taxizone_df.head(5)

(265, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265 entries, 0 to 264
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LocationID    265 non-null    int64
 1   Borough       265 non-null    object
 2   Zone          264 non-null    object
 3   service_zone  263 non-null    object
dtypes: int64(1), object(3)
memory usage: 8.4+ KB
None

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [35]:
holidaysfilepath = './work/Holidays.csv'
holidays_df = pd.read_csv(holidaysfilepath)
print(holidays_df.shape)
print(holidays_df.info())
holidays_df.head(5)

(13, 1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Holidays  13 non-null     object
dtypes: object(1)
memory usage: 232.0+ bytes
None

     Holidays
0  01-01-2022
1  01/17/2022
2  02/21/2022
3  05/30/2022
4  07/04/2022

# Data Exploration

Dimensions of dataset: rows and columns

In [36]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.5,0.50,0.5,0.00,0.0,None,0.3,4.80,2.0,1.0,0.00
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.5,0.50,0.5,0.00,0.0,None,0.3,10.80,2.0,1.0,0.00
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.5,3.25,0.5,4.60,0.0,None,0.3,23.15,1.0,1.0,2.75
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.0,0.50,0.5,0.00,0.0,None,0.3,9.30,2.0,1.0,0.00
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.0,0.50,0.5,5.21,0.0,None,0.3,31.26,1.0,1.0,2.75

In [37]:
taxizone_df.shape

(265, 4)

In [38]:
taxizone_df

     LocationID        Borough                     Zone service_zone
0             1            EWR           Newark Airport          EWR
1             2         Queens              Jamaica Bay    Boro Zone
2             3          Bronx  Allerton/Pelham Gardens    Boro Zone
3             4      Manhattan            Alphabet City  Yellow Zone
4             5  Staten Island            Arden Heights    Boro Zone
..          ...            ...                      ...          ...
260         261      Manhattan       World Trade Center  Yellow Zone
261         262      Manhattan           Yorkville East  Yellow Zone
262         263      Manhattan           Yorkville West  Yellow Zone
263         264        Unknown                       NV          NaN
264         265        Unknown                      NaN          NaN

[265 rows x 4 columns]

# Data Pre-processing

Merging Taxizone Data for Pickup.

In [39]:
#Pickup Location Zone Merge
df = df.merge(taxizone_df,how='left',left_on='PULocationID',right_on='LocationID')
df.drop(columns = ['LocationID'],axis = 1,inplace  = True)
df.rename(columns = {'Borough' : 'pickup_borough', 'Zone' : 'pickup_zone', 'service_zone' : 'pickup_service_zone'},inplace = True)
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,pickup_borough,pickup_zone,pickup_service_zone
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.50,...,0.0,None,0.3,4.80,2.0,1.0,0.00,Manhattan,Central Harlem North,Boro Zone
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.50,...,0.0,None,0.3,10.80,2.0,1.0,0.00,Manhattan,Hamilton Heights,Boro Zone
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.50,...,0.0,None,0.3,23.15,1.0,1.0,2.75,Manhattan,Central Harlem,Boro Zone
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.00,...,0.0,None,0.3,9.30,2.0,1.0,0.00,Brooklyn,Park Slope,Boro Zone
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.00,...,0.0,None,0.3,31.26,1.0,1.0,2.75,Brooklyn,Brooklyn Heights,Boro Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908608,2,2023-01-31 22:29:00,2023-01-31 22:42:00,None,NaN,49,62,NaN,4070.82,15.70,...,0.0,None,1.0,16.70,NaN,NaN,NaN,Brooklyn,Clinton Hill,Boro Zone
908609,2,2023-01-31 22:40:00,2023-01-31 22:48:00,None,NaN,10,205,NaN,2.14,4.41,...,0.0,None,1.0,5.41,NaN,NaN,NaN,Queens,Baisley Park,Boro Zone
908610,2,2023-01-31 23:46:00,2023-02-01 00:02:00,None,NaN,66,37,NaN,3.44,16.53,...,0.0,None,1.0,21.04,NaN,NaN,NaN,Brooklyn,DUMBO/Vinegar Hill,Boro Zone
908611,2,2023-01-31 23:01:00,2023-01-31 23:19:00,None,NaN,225,189,NaN,3.03,14.98,...,0.0,None,1.0,19.18,NaN,NaN,NaN,Brooklyn,Stuyvesant Heights,Boro Zone
908612,2,2023-01-31 23:51:00,2023-02-01 00:07:00,None,NaN,256,140,NaN,5.82,23.65,...,0.0,None,1.0,29.40,NaN,NaN,NaN,Brooklyn,Williamsburg (South Side),Boro Zone

Merging Taxizone Data for Dropoff.

In [40]:
#Pickup Location Zone Merge
df = df.merge(taxizone_df,how='left',left_on='DOLocationID',right_on='LocationID')
df.drop(columns = ['LocationID'],axis = 1,inplace  = True)
df.rename(columns = {'Borough' : 'drop_borough', 'Zone' : 'drop_zone', 'service_zone' : 'drop_service_zone'},inplace = True)
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,total_amount,payment_type,trip_type,congestion_surcharge,pickup_borough,pickup_zone,pickup_service_zone,drop_borough,drop_zone,drop_service_zone
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.50,...,4.80,2.0,1.0,0.00,Manhattan,Central Harlem North,Boro Zone,Manhattan,Central Harlem North,Boro Zone
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.50,...,10.80,2.0,1.0,0.00,Manhattan,Hamilton Heights,Boro Zone,Manhattan,Central Harlem,Boro Zone
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.50,...,23.15,1.0,1.0,2.75,Manhattan,Central Harlem,Boro Zone,Manhattan,Lenox Hill East,Yellow Zone
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.00,...,9.30,2.0,1.0,0.00,Brooklyn,Park Slope,Boro Zone,Brooklyn,Park Slope,Boro Zone
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.00,...,31.26,1.0,1.0,2.75,Brooklyn,Brooklyn Heights,Boro Zone,Manhattan,Murray Hill,Yellow Zone
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
908608,2,2023-01-31 22:29:00,2023-01-31 22:42:00,None,NaN,49,62,NaN,4070.82,15.70,...,16.70,NaN,NaN,NaN,Brooklyn,Clinton Hill,Boro Zone,Brooklyn,Crown Heights South,Boro Zone
908609,2,2023-01-31 22:40:00,2023-01-31 22:48:00,None,NaN,10,205,NaN,2.14,4.41,...,5.41,NaN,NaN,NaN,Queens,Baisley Park,Boro Zone,Queens,Saint Albans,Boro Zone
908610,2,2023-01-31 23:46:00,2023-02-01 00:02:00,None,NaN,66,37,NaN,3.44,16.53,...,21.04,NaN,NaN,NaN,Brooklyn,DUMBO/Vinegar Hill,Boro Zone,Brooklyn,Bushwick South,Boro Zone
908611,2,2023-01-31 23:01:00,2023-01-31 23:19:00,None,NaN,225,189,NaN,3.03,14.98,...,19.18,NaN,NaN,NaN,Brooklyn,Stuyvesant Heights,Boro Zone,Brooklyn,Prospect Heights,Boro Zone
908612,2,2023-01-31 23:51:00,2023-02-01 00:07:00,None,NaN,256,140,NaN,5.82,23.65,...,29.40,NaN,NaN,NaN,Brooklyn,Williamsburg (South Side),Boro Zone,Manhattan,Lenox Hill East,Yellow Zone

In [43]:
loc_cord = pd.read_csv('location_coordinates.csv')
drop_cord = pd.read_csv('drop_cord.csv')
df2 = df.merge(loc_cord,how='left',left_on='pickup_zone',right_on='pickup_zone')
df3 = df2.merge(drop_cord,how='left',left_on='drop_zone',right_on='drop_zone')
df3.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,pickup_borough,pickup_zone,pickup_service_zone,drop_borough,drop_zone,drop_service_zone,pickup_latitude,pickup_longitude,drop_latitude,drop_longitude
0,2,2022-01-01 00:14:21,2022-01-01 00:15:33,N,1.0,42,42,1.0,0.44,3.5,...,Manhattan,Central Harlem North,Boro Zone,Manhattan,Central Harlem North,Boro Zone,40.799218,-73.954900,40.799218,-73.954900
1,1,2022-01-01 00:20:55,2022-01-01 00:29:38,N,1.0,116,41,1.0,2.10,9.5,...,Manhattan,Hamilton Heights,Boro Zone,Manhattan,Central Harlem,Boro Zone,40.824145,-73.950062,61.472398,23.727168
2,1,2022-01-01 00:57:02,2022-01-01 01:13:14,N,1.0,41,140,1.0,3.70,14.5,...,Manhattan,Central Harlem,Boro Zone,Manhattan,Lenox Hill East,Yellow Zone,61.472398,23.727168,40.767262,-73.966522
3,2,2022-01-01 00:07:42,2022-01-01 00:15:57,N,1.0,181,181,1.0,1.69,8.0,...,Brooklyn,Park Slope,Boro Zone,Brooklyn,Park Slope,Boro Zone,40.670103,-73.985972,40.670103,-73.985972
4,2,2022-01-01 00:07:50,2022-01-01 00:28:52,N,1.0,33,170,1.0,6.26,22.0,...,Brooklyn,Brooklyn Heights,Boro Zone,Manhattan,Murray Hill,Yellow Zone,40.696085,-73.995028,NaN,NaN

In [45]:
df3.to_csv('final_data.csv')